services:
  web:
    image: ${DOCKER_HUB_USERNAME}/rag-book-assistant:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}

    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3