name: Python Application (Requirements & Tests)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      TESTING: "true"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip install -r requirements.txt
        python -m nltk.downloader punkt averaged_perceptron_tagger maxent_ne_chunker words
        
    - name: Update requirements
      run: |
        pip-compile --output-file=requirements.txt requirements.in
        
    - name: Check for requirements changes
      id: req-changes
      run: |
        if [[ -n $(git status --porcelain requirements.txt) ]]; then
          echo "Requirements file has changed"
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "No changes to requirements file"
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit requirements changes
      if: steps.req-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add requirements.txt
        git commit -m "Update requirements.txt via pip-compile"
        git push
        
    - name: Run tests
      run: |
        pip install pytest pytest-cov pytest-mock
        pytest --cov=./ --cov-report=xml -v
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml